### ISSUE TITLE
Ajout des offres OVH

### ISSUE THREAD

**Issue by centaureof40** [hardware/ovh-availability#3]
Bonjour,

 http://www.availability.ovh/

Gros dommage votre système ne fait pas OVH pourquoi ?
Vous faite KS, Sys, mais pas OVH pourquoi ?
J'espère que celà va changer car ça l'air très utile.

Merci de me tenir au courant.

**Comment by hardware** [comment]
Bonjour,

Parce que ça concerne très peu de monde, contrairement aux offres KIM/SYS, les offres OVH ne sont pas très accessibles au niveau du tarif pour le grand public, donc de ce fait, les serveurs sont généralement toujours disponibles, pas d'attente est demandée.

Ça pourrait être utile pour qu'elle offre par exemple ?

**Comment by centaureof40** [comment]
ben les Game de chez OVH, il sont toujours en sold out, ça fait 2 semaines que j'attends, j'ai vu des dispo, pas eu le temps de prendre que c'etait déjà sold out...

**Comment by centaureof40** [comment]
Y a souvent du sold out chez ovh sur les gamme à bas prix.

**Comment by hardware** [comment]
Voila j'ai ajouté les offres suivantes :

Ref | Offer
------------ |  -------------
150sp2 |  SP-32
140sp1 |  SP-64
140sp4 |  SP-128
140mg1 |  MG-128
140mg4 |  MG-256
150host1 |  HOST-32 
150host2 |  HOST-64
150host3 |  HOST-128
150mc1 |  MC-32
150mc2 |  MC-128-LD
150mc3 |  MC-128-HD
150mc4 |  MC-256-LD
150mc5 |  MC-256-HD
150eg4 |  EG-16
150eg1 |  EG-32
150eg2 |  EG-64
150eg3 |  EG-128
140fs1 |  FS-12T
140fs7 |  FS-30T
150fs1 |  FS-48T
150fs3 |  FS-72T
150fs5 |  FS-MAX
150mhg1 |  mini HG
150hg1 |   HG
150bhg1 |  BIG HG

**Comment by centaureof40** [comment]
merci beaucoup :)
