### ISSUE TITLE
Ajout du nombre d'unité livré dans "Offres disponibles récemment"

### ISSUE THREAD

**Issue by cnaslain** [hardware/ovh-availability#4]
Bonjour,

Après avoir passé quelques temps à rafraichir la page du limsufi pour voir quand des KS-4 seraient disponibles, je suis tombé sur cette application que je trouve indispensable!

Petite suggestion: Je ne sais pas si les infos sont dispo dans le retour de requête au webservice d'OVH; mais si c'est le cas, ce serait très utile d'ajouter au tableau "Offres disponibles récemment" le nombre d'unité livré. Celà permettrait de se rendre compte du volume/flux des kimsufi livrés.

Bonne continuation et merci pour cette application!

Chris

**Comment by hardware** [comment]
Désolé mais cette information ne peut pas être récupérée depuis les services d'OVH.
