### ISSUE TITLE
[IDEA] Would be cool to see what you are subscribed to.

### ISSUE THREAD

**Issue by GotDemBallsOfSteel** [hardware/ovh-availability#5]
It would be great that after logging in to Pushbullet on top, you could see your own subscriptions.
Like move the Pushbullet icon to the left, and add a block/table to the right of it, with "current subscriptions".  
There is no need to make it extra tall, or even wide (since OVH servers have short names), just use a script that allows multiple selection / scroll / etc.
  
Then you could select (and multi-select) there, and there would be a "remove" button.  
Example of these tables:  
https://datatables.net/examples/api/select_row.html  
https://jsfiddle.net/oscarj24/ctLm8/2/

**Comment by hardware** [comment]
Good idea, maybe I will add that feature this weekend.
