### ISSUE TITLE
Empty server after offer change

### ISSUE THREAD

**Issue by Wouter0100** [hardware/ovh-availability#7]
OVH changed the servers offered, and I see you already processed this in the website. The only downside now is, I've 2 pending requests which holds a empty server name..

**Comment by hardware** [comment]
Thank for reporting this, I changed the state of all pending request related with this old offers :

- 150sk10 (KS-1)
- 150sk20 (KS-2)
- 150sk22 (KS-2 SSD)
- 150sk30 (KS-3)
- 150sk40 (KS-4)
- 150sk50 (KS-5)
- 150sk60 (KS-6)

**Comment by Wouter0100** [comment]
Thanks, seems to be fixed! (y) Great product ;)
